---
- name: Postgres
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Install
      apt:
        package:
          - postgresql
          - postgresql-contrib
        state: latest
        update_cache: yes

    - name: Status
      service:
        name=postgresql
        state=started
        enabled=yes

    - name: Network
      ufw:
        rule: allow
        src: "{{ item }}"
      loop:
        - 10.231.0.0/16
        - 80.110.119.203/32