version: '3'

services:

  nginxGreen:
    container_name: nginxGreen
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./src/green.html:/usr/share/nginx/html/index.html

  nginxBlue:
    container_name: nginxBlue
    image: nginx
    ports:
      - 8001:80
    volumes:
      - ./src/blue.html:/usr/share/nginx/html/index.html

  haProxy:
    container_name: haProxy
    image: haproxy
    depends_on:
      - nginxGreen
      - nginxBlue
    ports:
      - 80:80
      - 1936:1936
    volumes:
      - ./src/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
